"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ReferenceLine,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { formatCountAxisCompact, formatMarketCap, formatNumber, formatUsd, formatUsdAxisCompact } from "@/lib/money";

type QuarterRow = {
  at: number;
  label: string;
  revenue: number | null;
  grossMarginPct: number | null;
  operatingMarginPct: number | null;
  netMarginPct: number | null;
  ebitdaMarginPct: number | null;
  cogsPctRevenue: number | null;
  sgaPctRevenue: number | null;
  rdPctRevenue: number | null;
  capex: number | null;
  operatingCashFlow: number | null;
  freeCashFlow: number | null;
  fcfMarginPct: number | null;
  debt: number | null;
  netDebtToEbitda: number | null;
  cashAndEquivalents: number | null;
  roePct: number | null;
  roicPct: number | null;
  roaPct: number | null;
  epsDiluted: number | null;
  shareCount: number | null;
  bookValuePerShare: number | null;
  fcfPerShare: number | null;
  revenueQoqPct: number | null;
  grossMarginQoqPct: number | null;
  operatingMarginQoqPct: number | null;
  netMarginQoqPct: number | null;
  ebitdaMarginQoqPct: number | null;
  cogsQoqPct: number | null;
  sgaQoqPct: number | null;
  rdQoqPct: number | null;
  capexQoqPct: number | null;
  ocfQoqPct: number | null;
  fcfQoqPct: number | null;
  fcfMarginQoqPct: number | null;
  debtQoqPct: number | null;
  netDebtToEbitdaQoqPct: number | null;
  cashQoqPct: number | null;
  roeQoqPct: number | null;
  roicQoqPct: number | null;
  roaQoqPct: number | null;
  epsQoqPct: number | null;
  sharesQoqPct: number | null;
  bvpsQoqPct: number | null;
  fcfPerShareQoqPct: number | null;
};

type Mode = "value" | "pct";
type ValueType = "currency" | "percent" | "ratio" | "number";

type MetricOption = {
  key: keyof QuarterRow;
  growthKey: keyof QuarterRow;
  label: string;
  info: string;
  valueType: ValueType;
};

type TrendCard = {
  id: string;
  title: string;
  color: string;
  options: MetricOption[];
};

type ChartPoint = { label: string; value: number; raw?: number };

const TREND_CARDS: TrendCard[] = [
  {
    id: "revenue",
    title: "Revenue",
    color: "#34d399",
    options: [{ key: "revenue", growthKey: "revenueQoqPct", label: "Revenue", info: "Quarterly total revenue.", valueType: "currency" }],
  },
  {
    id: "margins",
    title: "Margins",
    color: "#38bdf8",
    options: [
      { key: "grossMarginPct", growthKey: "grossMarginQoqPct", label: "Gross margin", info: "Gross profit as % of revenue.", valueType: "percent" },
      { key: "operatingMarginPct", growthKey: "operatingMarginQoqPct", label: "Operating margin", info: "Operating income as % of revenue.", valueType: "percent" },
      { key: "netMarginPct", growthKey: "netMarginQoqPct", label: "Net margin", info: "Net income as % of revenue.", valueType: "percent" },
      { key: "ebitdaMarginPct", growthKey: "ebitdaMarginQoqPct", label: "EBITDA margin", info: "EBITDA as % of revenue.", valueType: "percent" },
    ],
  },
  {
    id: "expenses",
    title: "Expenses",
    color: "#f59e0b",
    options: [
      { key: "cogsPctRevenue", growthKey: "cogsQoqPct", label: "COGS as % of revenue", info: "Cost of revenue divided by revenue.", valueType: "percent" },
      { key: "sgaPctRevenue", growthKey: "sgaQoqPct", label: "SG&A as % of revenue", info: "Selling, general, and admin expense divided by revenue.", valueType: "percent" },
      { key: "rdPctRevenue", growthKey: "rdQoqPct", label: "R&D as % of revenue", info: "Research and development divided by revenue.", valueType: "percent" },
      { key: "capex", growthKey: "capexQoqPct", label: "Capex", info: "Quarterly capital expenditures.", valueType: "currency" },
    ],
  },
  {
    id: "cashflow",
    title: "Cash Flow",
    color: "#8b5cf6",
    options: [
      { key: "operatingCashFlow", growthKey: "ocfQoqPct", label: "Operating cash flow", info: "Cash generated by operations per quarter.", valueType: "currency" },
      { key: "freeCashFlow", growthKey: "fcfQoqPct", label: "Free cash flow", info: "Operating cash flow minus capex.", valueType: "currency" },
      { key: "fcfMarginPct", growthKey: "fcfMarginQoqPct", label: "FCF margin", info: "Free cash flow as % of revenue.", valueType: "percent" },
    ],
  },
  {
    id: "balancesheet",
    title: "Balance Sheet",
    color: "#a78bfa",
    options: [
      { key: "debt", growthKey: "debtQoqPct", label: "Debt", info: "Total debt balance.", valueType: "currency" },
      { key: "netDebtToEbitda", growthKey: "netDebtToEbitdaQoqPct", label: "Net debt / EBITDA", info: "Leverage ratio using net debt and EBITDA.", valueType: "ratio" },
      { key: "cashAndEquivalents", growthKey: "cashQoqPct", label: "Cash & equivalents", info: "Cash and short-term equivalents.", valueType: "currency" },
    ],
  },
  {
    id: "return",
    title: "Return",
    color: "#06b6d4",
    options: [
      { key: "roePct", growthKey: "roeQoqPct", label: "ROE", info: "Return on equity.", valueType: "percent" },
      { key: "roicPct", growthKey: "roicQoqPct", label: "ROIC", info: "Return on invested capital.", valueType: "percent" },
      { key: "roaPct", growthKey: "roaQoqPct", label: "ROA", info: "Return on assets.", valueType: "percent" },
    ],
  },
  {
    id: "pershare",
    title: "Per Share",
    color: "#22c55e",
    options: [
      { key: "epsDiluted", growthKey: "epsQoqPct", label: "EPS (diluted)", info: "Diluted earnings per share.", valueType: "number" },
      { key: "shareCount", growthKey: "sharesQoqPct", label: "Share count", info: "Weighted diluted share count.", valueType: "number" },
      { key: "bookValuePerShare", growthKey: "bvpsQoqPct", label: "Book value / share", info: "Equity value divided by share count.", valueType: "currency" },
      { key: "fcfPerShare", growthKey: "fcfPerShareQoqPct", label: "FCF per share", info: "Free cash flow divided by share count.", valueType: "currency" },
    ],
  },
];

function formatValue(value: number | null, valueType: ValueType): string {
  if (value == null || !Number.isFinite(value)) return "—";
  if (valueType === "currency") return Math.abs(value) >= 1e9 ? formatMarketCap(value) : formatUsd(value);
  if (valueType === "percent") return `${formatNumber(value, 2)}%`;
  if (valueType === "ratio") return `${formatNumber(value, 2)}x`;
  return formatNumber(value, 2);
}

function formatAxisTick(v: number, valueType: ValueType, mode: Mode): string {
  if (mode === "pct") return `${formatNumber(v, 1)}%`;
  if (valueType === "currency") return formatUsdAxisCompact(v);
  if (valueType === "percent") return `${formatNumber(v, 1)}%`;
  if (valueType === "ratio") return `${formatNumber(v, 1)}x`;
  return formatCountAxisCompact(v);
}

function metricScalar(row: QuarterRow, opt: MetricOption, mode: Mode): number | null {
  const k = mode === "value" ? opt.key : opt.growthKey;
  const v = row[k];
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

function buildChartData(quarters: QuarterRow[], opt: MetricOption, mode: Mode): ChartPoint[] {
  const out: ChartPoint[] = [];
  for (const q of quarters) {
    const raw = metricScalar(q, opt, mode);
    if (raw == null || !Number.isFinite(raw)) continue;
    if (mode === "value") {
      out.push({ label: q.label, value: Math.abs(raw), raw });
    } else {
      out.push({ label: q.label, value: raw });
    }
  }
  return out;
}

function latestFromQuarters(quarters: QuarterRow[], opt: MetricOption, mode: Mode): number | null {
  for (let i = quarters.length - 1; i >= 0; i -= 1) {
    const v = metricScalar(quarters[i]!, opt, mode);
    if (v != null && Number.isFinite(v)) return v;
  }
  return null;
}

function InfoDot({ text }: { text: string }) {
  return (
    <span className="group relative inline-flex h-4 w-4 cursor-help items-center justify-center rounded-full border border-(--card-border) text-[10px] text-(--muted)">
      i
      <span className="pointer-events-none absolute left-1/2 top-5 z-20 hidden w-56 -translate-x-1/2 rounded-md border border-(--card-border) bg-(--background) p-2 text-xs text-(--muted) shadow-lg group-hover:block">
        {text}
      </span>
    </span>
  );
}

function TrendChart({
  quarters,
  metric,
  mode,
  compact,
  color,
}: {
  quarters: QuarterRow[];
  metric: MetricOption;
  mode: Mode;
  compact: boolean;
  color: string;
}) {
  const data = useMemo(() => buildChartData(quarters, metric, mode), [quarters, metric, mode]);
  const showAxes = !compact;
  const height = compact ? 290 : 560;
  const isPct = mode === "pct";
  const values = data.map((d) => d.value).filter((v) => Number.isFinite(v));
  const min = values.length ? Math.min(...values) : 0;
  const max = values.length ? Math.max(...values) : 1;
  const span = Math.max(0.001, max - min);
  const pad = span * 0.22;
  const yDomain: [number, number] = [min - pad, max + pad];
  const latestPctLegend = latestFromQuarters(quarters, metric, "pct");
  const latestValueLegend = latestFromQuarters(quarters, metric, "value");

  const legendFooter = isPct ? (
    <div className="mt-1 flex flex-wrap items-center justify-center gap-x-2 gap-y-1 px-1 text-center text-[11px] text-(--muted)">
      <span className="inline-flex items-center gap-1.5">
        <span className="inline-block h-2 w-2 shrink-0 rounded-sm" style={{ backgroundColor: color }} aria-hidden />
        <span className="font-medium text-foreground">{metric.label}</span>
      </span>
      <span className="text-(--muted)">·</span>
      <span>
        Latest QoQ:{" "}
        {latestPctLegend != null ? (
          <span className={"font-semibold " + (latestPctLegend < 0 ? "text-rose-300" : "text-emerald-300")}>
            {latestPctLegend > 0 ? "+" : ""}
            {formatNumber(latestPctLegend, 2)}%
          </span>
        ) : (
          <span className="text-foreground">—</span>
        )}
      </span>
    </div>
  ) : (
    <div className="mt-1 flex flex-wrap items-center justify-center gap-x-2 gap-y-1 px-1 text-center text-[11px] text-(--muted)">
      <span className="inline-flex items-center gap-1.5">
        <span className="inline-block h-2 w-2 shrink-0 rounded-sm" style={{ backgroundColor: color }} aria-hidden />
        <span className="font-medium text-foreground">{metric.label}</span>
      </span>
      <span className="text-(--muted)">·</span>
      <span>
        Latest: <span className="font-medium text-foreground">{formatValue(latestValueLegend, metric.valueType)}</span>
        {latestPctLegend != null ? (
          <span className={latestPctLegend < 0 ? " text-rose-300" : " text-emerald-300"}>
            {" "}
            ({latestPctLegend > 0 ? "+" : ""}
            {formatNumber(latestPctLegend, 2)}% QoQ)
          </span>
        ) : null}
      </span>
    </div>
  );

  if (!isPct) {
    return (
      <div className="w-full">
        <ResponsiveContainer width="100%" height={height}>
        <BarChart data={data} margin={{ top: 6, right: 4, left: 2, bottom: showAxes ? 30 : 2 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.12)" />
          <XAxis hide={!showAxes} dataKey="label" tick={{ fontSize: 10 }} angle={-25} textAnchor="end" height={44} />
          <YAxis
            hide={!showAxes}
            tick={{ fontSize: 9 }}
            width={showAxes ? 78 : 62}
            tickMargin={4}
            interval="preserveStartEnd"
            tickFormatter={(v) => formatAxisTick(Number(v), metric.valueType, mode)}
            domain={yDomain}
          />
          <Tooltip
            content={({ active, payload }) => {
              if (!active || !payload?.length) return null;
              const row = payload[0]?.payload as ChartPoint;
              const show = row.raw !== undefined && row.raw !== row.value ? row.raw : row.value;
              return (
                <div className="rounded-lg border border-(--card-border) bg-(--card) px-3 py-2 text-xs shadow-lg">
                  <p className="text-(--muted)">{row.label}</p>
                  <p className="mt-1 font-semibold">{formatValue(show, metric.valueType)}</p>
                </div>
              );
            }}
          />
          <Bar dataKey="value" fill={color} radius={[4, 4, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
        {legendFooter}
      </div>
    );
  }

  return (
    <div className="w-full">
      <ResponsiveContainer width="100%" height={height}>
      <LineChart data={data} margin={{ top: 6, right: 4, left: 2, bottom: showAxes ? 30 : 2 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.12)" />
        <ReferenceLine y={0} stroke="rgba(148,163,184,0.75)" strokeDasharray="4 4" />
        <XAxis hide={!showAxes} dataKey="label" tick={{ fontSize: 10 }} angle={-25} textAnchor="end" height={44} />
        <YAxis
          hide={!showAxes}
          tick={{ fontSize: 9 }}
          width={showAxes ? 58 : 52}
          tickMargin={4}
          interval="preserveStartEnd"
          tickFormatter={(v) => formatAxisTick(Number(v), metric.valueType, mode)}
          domain={yDomain}
        />
        <Tooltip
          content={({ active, payload }) => {
            if (!active || !payload?.length) return null;
            const row = payload[0]?.payload as ChartPoint;
            const g = row.value;
            return (
              <div className="rounded-lg border border-(--card-border) bg-(--card) px-3 py-2 text-xs shadow-lg">
                <p className="text-(--muted)">{row.label}</p>
                <p className={"mt-1 font-semibold " + (g < 0 ? "text-rose-300" : "text-emerald-300")}>
                  {`${g > 0 ? "+" : ""}${formatNumber(g, 2)}%`}
                </p>
              </div>
            );
          }}
        />
        <Line type="monotone" dataKey="value" stroke={color} strokeWidth={2} dot={false} connectNulls={false} />
      </LineChart>
    </ResponsiveContainer>
        {legendFooter}
    </div>
  );
}

function TrendCardView({
  card,
  quarters,
  mode,
  onModeChange,
  selectedKey,
  onSelectKey,
  onExpand,
}: {
  card: TrendCard;
  quarters: QuarterRow[];
  mode: Mode;
  onModeChange: (m: Mode) => void;
  selectedKey: keyof QuarterRow;
  onSelectKey: (k: keyof QuarterRow) => void;
  onExpand: (metric: MetricOption, mode: Mode) => void;
}) {
  const metric = card.options.find((o) => o.key === selectedKey) ?? card.options[0]!;

  return (
    <div className="flex min-h-[392px] flex-col rounded-xl border border-cyan-500/20 bg-gradient-to-br from-slate-900/90 via-slate-900 to-indigo-950/50 p-3 shadow-sm">
      <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-1.5">
          <p className="text-sm font-semibold">{card.title}</p>
          <InfoDot text={metric.info} />
        </div>
        <div className="flex flex-wrap items-center justify-end gap-1">
          <button
            type="button"
            onClick={() => onModeChange("value")}
            className={"rounded-md px-2 py-1 text-[11px] " + (mode === "value" ? "bg-cyan-500/30 text-cyan-100 ring-1 ring-cyan-400/40" : "border border-(--card-border)")}
          >
            $
          </button>
          <button
            type="button"
            onClick={() => onModeChange("pct")}
            className={"rounded-md px-2 py-1 text-[11px] " + (mode === "pct" ? "bg-violet-500/30 text-violet-100 ring-1 ring-violet-400/40" : "border border-(--card-border)")}
          >
            %
          </button>
          {card.options.length > 1 ? (
            <select
              value={String(metric.key)}
              onChange={(e) => onSelectKey(e.target.value as keyof QuarterRow)}
              className="max-w-[140px] rounded-md border border-(--card-border) bg-(--card) px-2 py-1 text-[11px]"
            >
              {card.options.map((o) => (
                <option key={String(o.key)} value={String(o.key)}>
                  {o.label}
                </option>
              ))}
            </select>
          ) : null}
          <button
            type="button"
            onClick={() => onExpand(metric, mode)}
            className="rounded-md border border-(--card-border) px-2 py-1 text-[11px] hover:bg-(--card)"
          >
            Expand
          </button>
        </div>
      </div>

      <div className="min-h-0 flex-1">
        <TrendChart quarters={quarters} metric={metric} mode={mode} compact color={card.color} />
      </div>
    </div>
  );
}

export function StockTrendsModal({
  symbol,
  open,
  onClose,
}: {
  symbol: string;
  open: boolean;
  onClose: () => void;
}) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [quarters, setQuarters] = useState<QuarterRow[]>([]);
  const [cardModes, setCardModes] = useState<Record<string, Mode>>({});
  const [selectedMetrics, setSelectedMetrics] = useState<Record<string, keyof QuarterRow>>({});
  const [expanded, setExpanded] = useState<{ cardId: string; selectedKey: keyof QuarterRow; mode: Mode } | null>(null);

  const sym = symbol.trim().toUpperCase();

  useEffect(() => {
    if (!open) {
      setExpanded(null);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError(null);
    fetch(`/api/stocks/${encodeURIComponent(sym)}/revenue-quarterly`)
      .then(async (res) => {
        const json = (await res.json()) as { quarters?: QuarterRow[]; error?: string };
        if (!res.ok) throw new Error(json.error ?? "Could not load trends.");
        return json.quarters ?? [];
      })
      .then((rows) => {
        if (cancelled) return;
        setQuarters(rows);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : "Could not load trends.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, sym]);

  useEffect(() => {
    const nextModes: Record<string, Mode> = {};
    const nextSelected: Record<string, keyof QuarterRow> = {};
    for (const c of TREND_CARDS) {
      nextModes[c.id] = cardModes[c.id] ?? "value";
      nextSelected[c.id] = selectedMetrics[c.id] ?? c.options[0]!.key;
    }
    setCardModes(nextModes);
    setSelectedMetrics(nextSelected);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!open) return null;

  return (
    <>
      <div className="fixed inset-0 z-[70] flex items-start justify-center overflow-y-auto bg-black/70 p-3 pt-8 sm:p-4 sm:pt-10" onClick={onClose}>
        <div className="relative w-full max-w-7xl rounded-2xl border border-cyan-500/35 bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950/70 p-3 shadow-xl sm:p-4" onClick={(e) => e.stopPropagation()}>
          <div className="mb-3 flex items-start justify-between gap-2">
            <div>
              <h3 className="text-lg font-semibold text-cyan-100">Chart Trends · {sym}</h3>
              <p className="text-xs text-slate-300">Quarterly fundamentals (cached + live)</p>
            </div>
            <button type="button" onClick={onClose} className="rounded-md border border-(--card-border) px-3 py-1 text-xs hover:bg-(--background)">
              Close
            </button>
          </div>

          {loading ? (
            <p className="py-12 text-center text-sm text-(--muted)">Loading trends…</p>
          ) : error ? (
            <p className="py-12 text-center text-sm text-red-400">{error}</p>
          ) : (
            <div className="grid gap-3 md:grid-cols-3">
              {TREND_CARDS.map((card) => (
                <TrendCardView
                  key={card.id}
                  card={card}
                  quarters={quarters}
                  mode={cardModes[card.id] ?? "value"}
                  onModeChange={(m) => setCardModes((s) => ({ ...s, [card.id]: m }))}
                  selectedKey={selectedMetrics[card.id] ?? card.options[0]!.key}
                  onSelectKey={(k) => setSelectedMetrics((s) => ({ ...s, [card.id]: k }))}
                  onExpand={(metric, mode) => setExpanded({ cardId: card.id, selectedKey: metric.key, mode })}
                />
              ))}
            </div>
          )}
        </div>
      </div>

      {expanded && quarters.length > 0 && (
        <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-4" onClick={() => setExpanded(null)}>
          <div className="relative flex max-h-[92vh] w-full max-w-6xl flex-col rounded-2xl border border-(--card-border) bg-(--card) p-4 shadow-xl" onClick={(e) => e.stopPropagation()}>
            {(() => {
              const card = TREND_CARDS.find((c) => c.id === expanded.cardId) ?? TREND_CARDS[0]!;
              const metric = card.options.find((o) => o.key === expanded.selectedKey) ?? card.options[0]!;
              return (
                <>
                  <div className="mb-2 flex flex-wrap items-center justify-end gap-2">
                    <div className="flex flex-wrap items-center gap-1">
                      <button
                        type="button"
                        onClick={() => setExpanded((s) => (s ? { ...s, mode: "value" } : s))}
                        className={"rounded-md px-2 py-1 text-xs " + (expanded.mode === "value" ? "bg-(--accent) text-(--accent-foreground)" : "border border-(--card-border)")}
                      >
                        $
                      </button>
                      <button
                        type="button"
                        onClick={() => setExpanded((s) => (s ? { ...s, mode: "pct" } : s))}
                        className={"rounded-md px-2 py-1 text-xs " + (expanded.mode === "pct" ? "bg-(--accent) text-(--accent-foreground)" : "border border-(--card-border)")}
                      >
                        %
                      </button>
                      {card.options.length > 1 ? (
                        <select
                          value={String(metric.key)}
                          onChange={(e) => setExpanded((s) => (s ? { ...s, selectedKey: e.target.value as keyof QuarterRow } : s))}
                          className="max-w-[200px] rounded-md border border-(--card-border) bg-(--card) px-2 py-1 text-xs"
                        >
                          {card.options.map((o) => (
                            <option key={String(o.key)} value={String(o.key)}>
                              {o.label}
                            </option>
                          ))}
                        </select>
                      ) : null}
                      <button type="button" onClick={() => setExpanded(null)} className="rounded-md border border-(--card-border) px-3 py-1 text-xs hover:bg-(--background)">
                        ✕
                      </button>
                    </div>
                  </div>
                  <div className="min-h-0 flex-1 overflow-hidden">
                    <TrendChart quarters={quarters} metric={metric} mode={expanded.mode} compact={false} color={card.color} />
                  </div>
                </>
              );
            })()}
          </div>
        </div>
      )}
    </>
  );
}
